language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
script: make test
install:
  - pip install . --use-mirrors
notifications:
  irc:
    channels:
      - "chat.freenode.net#asciinema"
    use_notice: true
    skip_join: true
