sudo: false
language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - pip install pep8

script:
  - find . -name \*.py -exec pep8 --ignore=E501 {} +
  - make test

notifications:
  irc:
    channels:
      - "chat.freenode.net#asciinema"
    use_notice: true
    skip_join: true
