sudo: false
language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

script: make test

notifications:
  irc:
    channels:
      - "chat.freenode.net#asciinema"
    use_notice: true
    skip_join: true
