sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

before_install:
  - pip install pycodestyle

script:
  - find . -name \*.py -exec pycodestyle --ignore=E501,E402 {} +
  - make test
